import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  ArrowRight,
  ChevronDown,
  HelpCircle,
  ListOrdered,
  Repeat,
  Sparkles,
  Target,
  TriangleAlert,
} from 'lucide-react';
import type { ExamPrepPlan } from '@studdybuddy/shared';
import {
  Badge,
  Button,
  Card,
  Chip,
  GlassPanel,
  Markdown,
  Progress,
} from '@renderer/components/ui';
import { cn } from '@renderer/lib/cn';
import { fadeSlideUp, staggerChildren } from '@renderer/lib/motion';
import { relativeTime } from '@renderer/lib/format';

/** Small labelled section wrapper with an icon eyebrow. */
function Section({
  icon,
  title,
  hint,
  children,
}: {
  icon: React.ReactNode;
  title: string;
  hint?: string;
  children: React.ReactNode;
}) {
  return (
    <motion.section variants={fadeSlideUp} className="space-y-3">
      <div className="flex items-center gap-2.5">
        <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-primary-soft text-primary">
          {icon}
        </span>
        <div>
          <h3 className="font-display text-base font-semibold text-t1">{title}</h3>
          {hint && <p className="text-xs text-t3">{hint}</p>}
        </div>
      </div>
      {children}
    </motion.section>
  );
}

export interface ExamPrepPlanViewProps {
  plan: ExamPrepPlan;
  /** Deep-link into a lecture's guided study experience. */
  onStudyLecture: (lectureId: string) => void;
  /** Send a likely question into "Ask your lectures". */
  onAskQuestion: (question: string) => void;
}

/**
 * Renders a full AI-generated {@link ExamPrepPlan}: the cumulative review,
 * ranked key concepts, recurring topics, likely exam questions, weak areas with
 * a weakness meter, and a recommended study order — all deep-linked so the
 * student can act on each recommendation immediately.
 */
export function ExamPrepPlanView({
  plan,
  onStudyLecture,
  onAskQuestion,
}: ExamPrepPlanViewProps) {
  const [openQuestion, setOpenQuestion] = useState<number | null>(null);

  return (
    <motion.div
      variants={staggerChildren}
      initial="hidden"
      animate="show"
      className="space-y-8"
    >
      {/* Cumulative review */}
      <Section
        icon={<Sparkles size={16} />}
        title="Cumulative review"
        hint={`Generated by ${plan.generatedBy} · ${relativeTime(plan.createdAt)}`}
      >
        <GlassPanel padding="lg">
          <Markdown>{plan.cumulativeReview}</Markdown>
        </GlassPanel>
      </Section>

      {/* Key concepts */}
      {plan.keyConcepts.length > 0 && (
        <Section
          icon={<Target size={16} />}
          title="Key concepts to master"
          hint="Ranked by how central they are to the course"
        >
          <motion.div
            variants={staggerChildren}
            className="grid gap-3 sm:grid-cols-2"
          >
            {plan.keyConcepts.map((c, i) => (
              <motion.div key={`${c.conceptName}-${i}`} variants={fadeSlideUp}>
                <Card
                  interactive
                  padding="md"
                  onClick={() => onStudyLecture(c.lectureId)}
                  role="button"
                  tabIndex={0}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      onStudyLecture(c.lectureId);
                    }
                  }}
                  className="group flex h-full flex-col gap-3"
                >
                  <div className="flex items-start gap-3">
                    <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-overlay text-sm font-semibold text-t2">
                      {i + 1}
                    </span>
                    <p className="font-medium text-t1">{c.conceptName}</p>
                  </div>
                  <div className="mt-auto space-y-1.5">
                    <div className="flex items-center justify-between text-[11px] text-t3">
                      <span>Importance</span>
                      <span className="font-medium text-t2">
                        {Math.round(c.importance * 100)}%
                      </span>
                    </div>
                    <Progress
                      value={c.importance}
                      size="sm"
                      aria-label={`Importance ${Math.round(c.importance * 100)} percent`}
                    />
                  </div>
                </Card>
              </motion.div>
            ))}
          </motion.div>
        </Section>
      )}

      {/* Recurring topics */}
      {plan.recurringTopics.length > 0 && (
        <Section
          icon={<Repeat size={16} />}
          title="Recurring topics"
          hint="Themes your professor kept coming back to"
        >
          <div className="flex flex-wrap gap-2">
            {plan.recurringTopics.map((topic) => (
              <Chip key={topic} leftIcon={<Repeat size={13} />}>
                {topic}
              </Chip>
            ))}
          </div>
        </Section>
      )}

      {/* Likely exam questions */}
      {plan.likelyExamQuestions.length > 0 && (
        <Section
          icon={<HelpCircle size={16} />}
          title="Likely exam questions"
          hint="Predicted from lecture emphasis — expand to practice"
        >
          <div className="space-y-2">
            {plan.likelyExamQuestions.map((q, i) => {
              const open = openQuestion === i;
              return (
                <GlassPanel key={i} padding="none" className="overflow-hidden">
                  <button
                    type="button"
                    onClick={() => setOpenQuestion(open ? null : i)}
                    aria-expanded={open}
                    className="focus-ring flex w-full items-center gap-3 px-4 py-3 text-left"
                  >
                    <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-gradient-primary-soft text-sm font-semibold text-primary">
                      {i + 1}
                    </span>
                    <span className="flex-1 text-sm font-medium text-t1">
                      {q}
                    </span>
                    <ChevronDown
                      size={18}
                      className={cn(
                        'shrink-0 text-t3 transition-transform duration-200',
                        open && 'rotate-180',
                      )}
                    />
                  </button>
                  {open && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      className="border-t border-stroke px-4 py-3"
                    >
                      <p className="text-sm text-t2">
                        Try answering this out loud in your own words first, then
                        check yourself against your lectures.
                      </p>
                      <Button
                        variant="secondary"
                        size="sm"
                        className="mt-3"
                        rightIcon={<ArrowRight size={15} />}
                        onClick={() => onAskQuestion(q)}
                      >
                        Ask your lectures
                      </Button>
                    </motion.div>
                  )}
                </GlassPanel>
              );
            })}
          </div>
        </Section>
      )}

      {/* Weak areas */}
      {plan.weakAreas.length > 0 && (
        <Section
          icon={<TriangleAlert size={16} />}
          title="Weak areas to shore up"
          hint="Where you've slipped — worth extra attention"
        >
          <div className="space-y-3">
            {plan.weakAreas.map((w) => (
              <Card key={w.conceptId} padding="md" className="space-y-3">
                <div className="flex items-start justify-between gap-4">
                  <div className="space-y-1">
                    <p className="font-medium text-t1">{w.conceptName}</p>
                    <p className="text-sm text-t3">{w.reason}</p>
                  </div>
                  <Badge variant="rose" solid>
                    {Math.round(w.weakness * 100)}% weak
                  </Badge>
                </div>
                <div className="flex items-center gap-3">
                  <div className="flex-1">
                    <Progress
                      value={w.weakness}
                      variant="solid"
                      size="sm"
                      aria-label={`Weakness ${Math.round(w.weakness * 100)} percent`}
                      className="[&>div]:bg-rose"
                    />
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    rightIcon={<ArrowRight size={15} />}
                    onClick={() => onStudyLecture(w.lectureId)}
                  >
                    Study this
                  </Button>
                </div>
              </Card>
            ))}
          </div>
        </Section>
      )}

      {/* Recommended study order */}
      {plan.studyOrder.length > 0 && (
        <Section
          icon={<ListOrdered size={16} />}
          title="Recommended study order"
          hint="Work through these in sequence for the best payoff"
        >
          <ol className="relative space-y-3 border-l border-stroke pl-6">
            {plan.studyOrder.map((step, i) => (
              <li key={i} className="relative">
                <span className="absolute -left-[31px] flex h-6 w-6 items-center justify-center rounded-full border border-stroke bg-surface text-xs font-semibold text-t2">
                  {i + 1}
                </span>
                <Card padding="md" className="flex items-start justify-between gap-4">
                  <div className="space-y-1">
                    <p className="font-medium text-t1">{step.title}</p>
                    <p className="text-sm text-t3">{step.rationale}</p>
                  </div>
                  {step.lectureId && (
                    <Button
                      variant="ghost"
                      size="sm"
                      rightIcon={<ArrowRight size={15} />}
                      onClick={() => onStudyLecture(step.lectureId as string)}
                    >
                      Open
                    </Button>
                  )}
                </Card>
              </li>
            ))}
          </ol>
        </Section>
      )}
    </motion.div>
  );
}
