import { afterEach, describe, expect, it } from 'vitest';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { AskPanel } from './AskPanel';

afterEach(cleanup);

/**
 * Regression test for the `?q=` deep-link: a question passed via `initialQuestion`
 * (Smart Review → "Ask your lectures") must auto-run and surface a grounded
 * answer, rather than being silently dropped.
 */
describe('AskPanel deep-link', () => {
  it('auto-asks the initial question and renders an answer', async () => {
    render(
      <MemoryRouter>
        <AskPanel scope={{}} initialQuestion="What does DNA polymerase do?" />
      </MemoryRouter>,
    );

    // The question appears immediately as a posed entry…
    expect(await screen.findByText('What does DNA polymerase do?')).toBeInTheDocument();
    // …and the mock backend actually answers it (every answer card carries a
    // "Generated by …" footer), proving the deep-linked question wasn't dropped.
    await waitFor(() => expect(screen.getByText(/Generated by/i)).toBeInTheDocument(), {
      timeout: 3000,
    });
  });
});
